package usps

import (
	"fmt"
)

type XMLError struct {
	Number      string // Error number generated by the Web Tools server.
	Source      string // Component & interface that generated the error on the Web Tools server.
	Description string // Error description
	HelpFile    string // (Reserved for future use)
	HelpContext string // (Reserved for future use)
}

func (e *XMLError) Error() string {
	return fmt.Sprintf("(%s: %s) %s", e.Number, e.Source, e.Description)
}
